' ============================================================================
' GENERATED by the one-off scan documented below -- reviewed and committed, not
' regenerated on every build. Emitted by assemble.py immediately before
' src/module_body/tail.bmx, i.e. after every Global is declared and before any
' game code runs.
'
' WHAT THESE ARE
' Module-scope collection Globals that the corpus USES (367 call sites in total)
' but never ASSIGNS anywhere. In the original they were declared with an
' initialiser in the module body -- they are part of the 30 module Globals whose
' initialiser expressions were never decoded (module_globals_decoded.tsv covers
' only the 64 that reduce to a bare array allocation). Left Null, the first
' method call on any of them throws "Attempt to access field or method of Null
' object". That is exactly how the boot died in TSnowFlake.New:
'     g_snowflakes.AddLast(Self)
'
' WHY CreateList()/CreateMap() IS THE RIGHT DEFAULT
' Each of these is only ever read via AddLast / Remove / Clear / Count / EachIn.
' Nothing assigns them, so the original cannot have been filling them from
' elsewhere -- an empty collection at start-up is the only reading consistent
' with the code. TMyGfxModes.New shows the same intent explicitly in a body that
' IS recovered: "If Not g_gfxmodes Then g_gfxmodes = CreateList()".
'
' KNOWN LIMITATION -- READ THIS BEFORE TRUSTING IT
' Several entries below are the SAME original slot under different recovered
' names: g_clubs/g_clublist, g_players/g_allplayers/g_playerlist,
' g_horses/g_allhorses/g_horselist/g_stable_horselist,
' g_competitions/g_comps/g_complist/g_allcompetitions/g_lcompetitions,
' g_snowflakes/g_snowlist, g_trainobjs/g_trainingobjects/g_trainingobs/g_trainobs
' and more. Giving each its own list stops the crashes but does NOT make them
' share data -- a body that fills g_clubs and a body that reads g_clublist still
' see different lists. That is a separate, larger defect; run
' scripts/unify_globals.py for the full report. Fixing it needs per-file,
' per-address edits, not a sweep.
' ============================================================================
g_achievements = CreateList()
g_allcompetitions = CreateList()
g_allgadgets = CreateList()
g_allhorses = CreateList()
g_allplayers = CreateList()
g_balls = CreateList()
g_bj_cardlist = CreateList()
g_bj_dealercards = CreateList()
g_bj_dealerhand = CreateList()
g_bj_playerhand = CreateList()
g_bossmessages = CreateList()
g_bossmsg_list = CreateList()
g_bossmsgs = CreateList()
g_cameraman_list = CreateList()
g_cards = CreateList()
g_clublist = CreateList()
g_clubs = CreateList()
g_competitions = CreateList()
g_complist = CreateList()
g_comps = CreateList()
g_cones = CreateList()
g_continents = CreateList()
g_contractoffers = CreateList()
g_deck = CreateList()
g_drawobs = CreateList()
g_dummies = CreateList()
g_gadgets = CreateList()
g_gfxmodes = CreateList()
g_hand1 = CreateList()
g_hand2 = CreateList()
g_horselist = CreateList()
g_horses = CreateList()
g_langmap = CreateMap()
g_lcompetitions = CreateList()
g_messages = CreateList()
g_nationlist = CreateList()
g_nations = CreateList()
g_object133 = CreateList()
g_object280 = CreateList()
g_object60 = CreateList()
g_object79 = CreateList()
g_object813 = CreateList()
g_object851 = CreateList()
g_offers = CreateList()
g_pairicons = CreateList()
g_pairs_icons = CreateList()
g_photographers = CreateList()
g_playerlist = CreateList()
g_players = CreateList()
g_poles = CreateList()
g_replay = CreateList()
g_replayballs = CreateList()
g_replayplayers = CreateList()
g_reslist = CreateList()
g_runners = CreateList()
g_screenmessages = CreateList()
g_screens = CreateList()
g_snowflakes = CreateList()
g_snowlist = CreateList()
g_stable_horselist = CreateList()
g_stable_racelist = CreateList()
g_stadiums = CreateList()
g_training_lines = CreateList()
g_traininglines = CreateList()
g_trainingobjects = CreateList()
g_trainingobs = CreateList()
g_trainobjs = CreateList()
g_trainobs = CreateList()
g_zonelist = CreateList()
