#!/usr/bin/env python3
"""
build_dependency_graph.py -- turn the raw Ghidra call-graph observation into the
reconstruction dependency graph.

    python scripts/build_dependency_graph.py             # rebuild the TSVs
    python scripts/build_dependency_graph.py --render    # ... and re-render the document
    python scripts/build_dependency_graph.py --render <template> <target>

INPUTS
  extracted/vtable_map.tsv                   slot -> code address (generated by resolve_vtables.py)
  extracted/class_tables.tsv                 class table VA, super, instance size
  extracted/object_model.json                fields (offset + type sig) and method signatures
  extracted/ghidra/function_inventory.tsv    every function, size, caller counts
  extracted/callgraph/callgraph_functions.tsv
  extracted/callgraph/callgraph_direct.tsv
  extracted/callgraph/callgraph_indirect.tsv
  extracted/callgraph/callgraph_globalstores.tsv

OUTPUTS (all into extracted/)
  callgraph_resolved.tsv     one row per call edge, with the resolution and its evidence
  callgraph_unresolved.tsv   the indirect sites we could NOT resolve, with why
  globals_typed.tsv          module-level Global VA -> inferred type + evidence
  dep_layers.tsv             per function: scc, layer, in-scope fan-in/fan-out
  type_deps.tsv              Type -> Type edges from field types and method signatures
  type_layers.tsv            per Type: scc, layer
  leaves.tsv                 functions with no in-scope callees
  vertical_slice.tsv         functions reachable from the boot/menu/match roots
  work_units.tsv             proposed pass-sized batches

DOCUMENT (--render only)
  The reconstruction dependency-graph document (TARGET below, overridable on the
  command line) is rewritten from the TSVs above, so the published document cannot
  drift from the data. Every table in it is generated; only the prose is hand-written,
  in scripts/templates/11-reconstruction-dependency-graph.template.md with <<<name>>>
  markers. Rendering is the second half of one pipeline, which is why it lives here
  rather than in a separate script.

RESOLUTION MODEL (indirect calls)
  Legacy BlitzMax method dispatch is  `mov R,[Self] ; call dword ptr [R + slot]`.
  NSS5CallGraph.java recorded, per site, the slot and a backward def-use chain ending in a
  terminal (PARAM+0x8 = Self, PARAM+0xN, GLOBAL:VA, RETVAL:VA, IMM:VA, LOCAL...).
  Here we turn the terminal + the intervening field/array derefs into a static receiver
  TYPE, then look the slot up in that type's merged (own + inherited) slot table.
  Everything that cannot be typed is reported, not guessed.
"""

import io, os, sys, json, csv, re, struct
from collections import defaultdict, deque, Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EX   = os.path.join(ROOT, "extracted")
CG   = os.path.join(EX, "callgraph")
TEMPLATE = os.path.join(ROOT, "scripts", "templates",
                        "11-reconstruction-dependency-graph.template.md")
TARGET   = os.path.join(ROOT, "docs", "specs", "11-reconstruction-dependency-graph.md")

# ---- command line ----------------------------------------------------------
# Checked before the (slow) analysis runs, so a mistyped flag fails immediately
# instead of after a full rebuild.
RENDER = "--render" in sys.argv
POSARGS = [a for a in sys.argv[1:] if not a.startswith("-")]
for _a in sys.argv[1:]:
    if _a.startswith("-") and _a != "--render":
        sys.exit("usage: build_dependency_graph.py [--render [template [target]]]")

# ---- section / scope constants (all re-derived, see doc) --------------------
TEXT_LO, TEXT_HI = 0x00401000, 0x004B9788      # BlitzMax C runtime (.text)
CODE_LO, CODE_HI = 0x004BA000, 0x005B9723      # all BlitzMax-compiled code
GAME_HI          = 0x0058DBF3                  # first module-type slot; below = NSS5's own code
GAME_CT_HI       = 0x00C94988                  # class tables below this are NSS5's own types
ABSTRACT_STUB    = 0x005B95AC

# Roots of the minimum vertical slice: boot -> menu -> load a real club -> play a match.
ANCHOR_GROUPS = {
    "boot":  [("TLocale", "SetUp"), ("TOptions", "SetUp"), ("TOptions", "LoadOptions"),
              ("TGadget", "SetUp"), ("TScreen", "SetUp"), ("TScreen", "SetUpFonts")],
    "menu":  [("TScreen", "SetActive"), ("TScreen", "Update"), ("TScreen", "Render"),
              ("TScreen", "GetInput"), ("TScreen_MainMenu", "CreateScreen"),
              ("TScreen_MainMenu", "SetUpScreen"), ("TScreen_MainMenu", "Update"),
              ("TScreen_MainMenu", "NewGame")],
    "data":  [("TContinent", "LoadData"), ("TNation", "LoadData"), ("TClub", "LoadData"),
              ("TCompetition", "LoadData"), ("TStadium", "LoadData"),
              ("TPromotionPlace", "LoadData"), ("TTeamPool", "LoadData"),
              ("TCompetition", "SetUpCompetitionsAll"), ("TTeam", "CreateSquadSimple")],
    "match": [("TEngine", "SetUp"), ("TEngine", "SetUpMatch"), ("TEngine", "MatchLoop"),
              ("TEngine", "Update"), ("TEngine", "Render"), ("TEngine", "CheckInput"),
              ("TEngine", "MatchOver"), ("TEngine", "EndMatch"),
              ("TCompetition", "PlayFixtures")],
}
ANCHOR_METHODS = [tm for g in ANCHOR_GROUPS.values() for tm in g]

def rd_tsv(path):
    with io.open(path, encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))

def H(v):  return "0x%08x" % v
def ihex(s):
    s = (s or "").strip()
    if not s: return None
    try: return int(s, 16)
    except ValueError: return None

# ============================================================================
# 1. Type model
# ============================================================================

model = json.load(io.open(os.path.join(EX, "object_model.json"), encoding="utf-8-sig"))
vmap  = rd_tsv(os.path.join(EX, "vtable_map.tsv"))
ctab  = rd_tsv(os.path.join(EX, "class_tables.tsv"))

ct_va      = {r["type"]: int(r["classtable_va"], 16) for r in ctab}
super_of   = {r["type"]: (r["super_type"] if r["super_type"] != "Object(runtime)" else None) for r in ctab}
inst_size  = {r["type"]: int(r["instance_size"]) for r in ctab}
va2type    = {v: t for t, v in ct_va.items()}
GAME_TYPES = {t for t, v in ct_va.items() if v < GAME_CT_HI}
REAL_GAME_TYPES = {t for t in GAME_TYPES if not t.startswith("z_")}

fields_of  = defaultdict(list)   # type -> [(offset, name, sig)]
own_slots  = defaultdict(dict)   # type -> {slot: (kind,name,sig)}
for e in model:
    for m in e["members"]:
        if m["kind"] == "Field":
            fields_of[e["type"]].append((m["offset"], m["name"], m["sig"]))
        else:
            own_slots[e["type"]][m["offset"]] = (m["kind"], m["name"], m["sig"])

slot_va = defaultdict(dict)      # type -> {slot: va}
slot_status = defaultdict(dict)
for r in vmap:
    va = ihex(r["va"])
    slot_va[r["type"]][int(r["slot"], 16)] = va
    slot_status[r["type"]][int(r["slot"], 16)] = r["status"]

def ancestry(t):
    out, seen = [], set()
    while t and t not in seen:
        seen.add(t); out.append(t); t = super_of.get(t)
    return out

# merged (own + inherited) slot table per type
FULL = {}      # type -> {slot: (owner_type, kind, name, sig, va)}
for t in ct_va:
    acc = {}
    for anc in reversed(ancestry(t)):            # base first, derived overrides
        for s, (k, n, g) in own_slots.get(anc, {}).items():
            acc[s] = (anc, k, n, g, slot_va[anc].get(s))
    # a derived type re-points inherited slots in its own class table, so prefer its VA
    for s in list(acc):
        if s in slot_va.get(t, {}):
            o, k, n, g, _ = acc[s]
            acc[s] = (o, k, n, g, slot_va[t][s])
    FULL[t] = acc

subtypes = defaultdict(set)
for t in ct_va:
    for anc in ancestry(t)[1:]:
        subtypes[anc].add(t)

# address -> the slot(s) that point at it
addr2slot = defaultdict(list)
for r in vmap:
    va = ihex(r["va"])
    if va and r["status"] == "OK":
        addr2slot[va].append((r["type"], r["kind"], r["name"], r["sig"], int(r["slot"], 16)))

def label_of(va):
    ss = addr2slot.get(va)
    if ss:
        t, k, n, g, s = ss[0]
        extra = ("+%d" % (len(ss) - 1)) if len(ss) > 1 else ""
        return "%s.%s%s" % (t, n, extra)
    return None

# ---- signature parsing -----------------------------------------------------
def split_args(argstr):
    out, depth, cur = [], 0, ""
    for ch in argstr:
        if ch == "(" or ch == "[": depth += 1
        elif ch == ")" or ch == "]": depth -= 1
        if ch == "," and depth == 0:
            out.append(cur); cur = ""
        else:
            cur += ch
    if cur.strip(): out.append(cur)
    return [a for a in out if a != ""]

def parse_sig(sig):
    """'(:TFixture,:TTeam,:TTeam,()i)i' -> (['(:TFixture','..'], 'i')"""
    if not sig or not sig.startswith("("): return [], sig or ""
    depth = 0
    for i, ch in enumerate(sig):
        if ch == "(": depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return split_args(sig[1:i]), sig[i + 1:]
    return [], ""

def type_of_sig(s):
    """Object type named by a signature fragment, else None."""
    s = (s or "").strip()
    while s.startswith("[]") or s.startswith("*"):
        s = s[2:] if s.startswith("[]") else s[1:]
    if s.startswith(":"): return s[1:]
    return None

def elem_type_of_sig(s):
    s = (s or "").strip()
    if s.startswith("[]"): return type_of_sig(s[2:])
    return None

ARGSZ = {"l": 8, "d": 8}
def param_offsets(sig, is_method):
    """stack offset -> signature fragment, cdecl, Self at +8 for Methods."""
    args, _ = parse_sig(sig)
    off, out = 8, {}
    if is_method:
        out[8] = "SELF"; off = 12
    for a in args:
        out[off] = a
        off += ARGSZ.get(a.strip(), 4)
    return out

# field lookup by byte offset, searching the whole ancestry
# ============================================================================
# 2. Raw call-graph observation
# ============================================================================

fn_rows  = rd_tsv(os.path.join(CG, "callgraph_functions.tsv"))
direct   = rd_tsv(os.path.join(CG, "callgraph_direct.tsv"))
indirect = rd_tsv(os.path.join(CG, "callgraph_indirect.tsv"))
gstores  = rd_tsv(os.path.join(CG, "callgraph_globalstores.tsv"))
callargs = rd_tsv(os.path.join(CG, "callgraph_callargs.tsv"))

# Runtime helpers identified by disassembly while building this graph:
BB_OBJECT_NEW      = 0x004A8F20   # bbObjectNew(BBClass*)      -> allocates, calls slot 0x10
BB_OBJECT_DOWNCAST = 0x004A8F60   # bbObjectDowncast(obj, BBClass*) -> obj or the null singleton
BB_ARRAY_NEW       = 0x004A63D0   # bbArrayNew(const char *type_tag, ndims, sizes) -> BBArray
NULL_OBJECT        = 0x005C9C80

# --- minimal PE reader, only needed to follow bbArrayNew's type-tag string ---
_PE = open(os.path.join(ROOT, "binary", "NSS5.exe"), "rb").read()
_e  = struct.unpack_from("<I", _PE, 0x3C)[0]
_IMG = struct.unpack_from("<I", _PE, _e + 24 + 28)[0]
_SECS = []
_so = _e + 24 + struct.unpack_from("<H", _PE, _e + 20)[0]
for _i in range(struct.unpack_from("<H", _PE, _e + 6)[0]):
    _o = _so + _i * 40
    _vs, _rva, _rs, _ro = struct.unpack_from("<IIII", _PE, _o + 8)
    _SECS.append((_IMG + _rva, _vs, _ro, _rs))

def rd32_at(va):
    for base, vs, ro, rs in _SECS:
        if base <= va < base + vs and va - base + 4 <= rs:
            return struct.unpack_from("<I", _PE, ro + (va - base))[0]
    return None

def cstr_at(va, lim=64):
    for base, vs, ro, rs in _SECS:
        if base <= va < base + vs and va - base < rs:
            o = ro + (va - base); x = o
            while x < len(_PE) and 32 <= _PE[x] < 127 and x - o < lim: x += 1
            return _PE[o:x].decode("ascii") if x < len(_PE) and _PE[x] == 0 else None
    return None

ARGS = {}   # call site VA -> (callee VA, [imm arg or None, ...])
for r in callargs:
    ARGS[ihex(r["site"])] = (ihex(r["callee"]),
                             [ihex(r["arg0"]), ihex(r["arg1"]), ihex(r["arg2"]), ihex(r["arg3"])])

def type_from_helper(site):
    """
    Static type of the value a runtime-helper call at `site` produces.
    For an ARRAY the element type is returned, matching the convention used for
    array-typed fields (a call through an array value is always on an element).
    """
    e = ARGS.get(site)
    if not e: return None
    callee, a = e
    if callee == BB_OBJECT_NEW      and a[0] is not None: return va2type.get(a[0])
    if callee == BB_OBJECT_DOWNCAST and a[1] is not None: return va2type.get(a[1])
    if callee == BB_ARRAY_NEW       and a[0] is not None:
        tag = cstr_at(a[0])
        return type_of_sig(tag) if tag else None
    return None

FN = {}
for r in fn_rows:
    a = ihex(r["addr"])
    FN[a] = dict(addr=a, name=r["name"], section=r["section"], size=int(r["size"]),
                 ninsn=int(r["ninsn"]))

def in_game(a):
    return a is not None and CODE_LO <= a < GAME_HI

def scope_of(a):
    if a is None: return "?"
    if in_game(a): return "game"
    if CODE_LO <= a < CODE_HI: return "module"      # BRL/PUB/3rd-party BlitzMax
    if TEXT_LO <= a <= TEXT_HI: return "runtime"    # BlitzMax C runtime
    return "extern"

# caller function -> its declaring type (if the caller is itself a known slot body)
def caller_type(a):
    ss = addr2slot.get(a)
    if not ss: return None, None, None
    t, k, n, g, s = ss[0]
    return t, k, g

# ============================================================================
# 3. Resolve indirect (virtual) call sites -- iterative fixpoint
# ============================================================================
# A receiver value is identified by a "value key":
#     ("param", caller_va, ebp_offset)   ("global", G)   ("ret", call_site)   ("imm", v)
# Seeds come from signatures and from the two runtime helpers whose class-table
# argument we recovered (bbObjectNew / bbObjectDowncast). Each site we resolve teaches
# us the return type of the call at that site, which seeds further sites, so we iterate
# to a fixpoint. Nothing is guessed: an unresolvable key stays unresolved and is
# reported in callgraph_unresolved.tsv.

STEP = re.compile(r"^([A-Z]{3})=\[([A-Z]{3})(\+idx)?\+(-?0x[0-9a-f]+)\]$")

def parse_chain(chain):
    """-> ordered field derefs [(disp, is_index)], BBClass load and terminal removed."""
    derefs, seen_vt = [], False
    for st in (c for c in chain.split(";") if c):
        m = STEP.match(st)
        if not m: continue
        src, idx, disp = m.group(2), m.group(3), int(m.group(4), 16)
        if src in ("EBP", "ESP"): continue
        if not seen_vt and disp == 0 and not idx:
            seen_vt = True; continue
        derefs.append((disp, bool(idx)))
    return derefs

class Site(object):
    __slots__ = ("caller", "site", "slot", "term", "chain", "derefs", "vkey", "cleanup")

sites = []
for r in indirect:
    if r["form"] == "abs" and r["vt"] == "0":
        continue                                   # IAT / import call
    s = Site()
    s.caller = ihex(r["caller"]); s.site = ihex(r["site"])
    s.term = r["term"]; s.chain = r["chain"]
    s.slot = int(r["slot"], 16) if (r["vt"] == "1" and r["slot"]) else None
    s.cleanup = int(r.get("cleanup", "-1") or -1)
    s.derefs = parse_chain(r["chain"]) if s.slot is not None else []
    t = s.term
    if   t.startswith("PARAM+"):  s.vkey = ("param", s.caller, int(t[6:], 16))
    elif t.startswith("GLOBAL:"): s.vkey = ("global", ihex(t[7:]))
    elif t.startswith("RETVAL:") and "@" in t: s.vkey = ("ret", ihex(t.split("@")[1]))
    elif t.startswith("IMM:"):    s.vkey = ("imm", ihex(t[4:]))
    else:                         s.vkey = None
    sites.append(s)

TYPEOF, EVID = {}, {}
DIRECT_AT = {ihex(r["site"]): ihex(r["callee"]) for r in direct if r["kind"] == "call"}

def sig_ret_type(callee):
    cands = {type_of_sig(parse_sig(g)[1]) for (_t, _k, _n, g, _s) in addr2slot.get(callee, [])}
    cands.discard(None)
    return cands.pop() if len(cands) == 1 else None

def learn(k, t, ev):
    if t and k not in TYPEOF:
        TYPEOF[k] = t; EVID[k] = ev; return 1
    return 0

# ---- seed A: parameters, from the caller's own recovered signature ----------
for s in sites:
    if not s.vkey or s.vkey[0] != "param" or s.vkey in TYPEOF: continue
    ct, ck, cg = caller_type(s.caller)
    if ct is None: continue
    frag = param_offsets(cg, ck == "Method").get(s.vkey[2])
    if frag is None: continue
    if frag == "SELF": learn(s.vkey, ct, "self")
    else:              learn(s.vkey, type_of_sig(frag), "param-sig")

# ---- seed B: call return values --------------------------------------------
for s in sites:
    if not s.vkey or s.vkey[0] != "ret" or s.vkey in TYPEOF: continue
    sv = s.vkey[1]
    if learn(s.vkey, type_from_helper(sv), "helper-classtable"): continue
    learn(s.vkey, sig_ret_type(DIRECT_AT.get(sv)), "callee-sig")

# ---- seed C: module-level Globals, from the stores that fill them -----------
# NOTE: extract_globals.py proves NSS5.exe carries NO BBDEBUGDECL_GLOBAL records, so a
# Global's declared type is not recoverable from metadata. The only evidence is (a) what
# gets stored into it and (b) what gets called through it.
GSTORE_SRC = defaultdict(list)      # global VA -> [inner call site VA]
for r in gstores:
    g = ihex(r["global"])
    if g is None: continue
    if r["term"].startswith("RETVAL:") and "@" in r["term"]:
        GSTORE_SRC[g].append(ihex(r["term"].split("@")[1]))

def seed_globals_from_stores():
    n = 0
    for g, srcs in GSTORE_SRC.items():
        if ("global", g) in TYPEOF: continue
        for sv in srcs:
            u = (type_from_helper(sv) or sig_ret_type(DIRECT_AT.get(sv))
                 or TYPEOF.get(("ret", sv)))
            if u:
                n += learn(("global", g), u, "store-from-" + H(sv))
                break
    return n

seed_globals_from_stores()

# ---- seed D: class-table immediates (static Function call on a Type) --------
for s in sites:
    if s.vkey and s.vkey[0] == "imm":
        learn(s.vkey, va2type.get(s.vkey[1]), "classtable-imm")

# ---- resolution machinery ---------------------------------------------------
# merged field table per type (own + inherited), offset -> (owner, name, sig)
FIELDS = {}
for t in ct_va:
    acc = {}
    for anc in reversed(ancestry(t)):
        for o, n, g in fields_of.get(anc, []):
            acc[o] = (anc, n, g)
    FIELDS[t] = acc

def field_at(t, off):
    return FIELDS.get(t, {}).get(off)

def apply_path(base, derefs):
    cur, trail = base, ""
    for disp, isidx in reversed(derefs):
        if isidx: continue          # BBArray element read; the array itself was the field
        f = field_at(cur, disp)
        if f is None: return None, "field+%#x-not-in-%s" % (disp, cur)
        owner, fname, fsig = f
        nxt = elem_type_of_sig(fsig) or type_of_sig(fsig)
        if nxt is None: return None, "field-%s.%s-not-object" % (owner, fname)
        cur = nxt; trail += "/%s.%s" % (owner, fname)
    return cur, trail

WHY = {"param": "param-untyped", "global": "global-untyped",
       "ret": "retval-untyped", "imm": "imm-not-classtable"}

def resolve_site(s):
    if s.slot is None: return None, "not-virtual-dispatch"
    if s.vkey is None: return None, "terminal:" + s.term.split(":")[0].split("@")[0]
    base = TYPEOF.get(s.vkey)
    if base is None: return None, WHY[s.vkey[0]]
    recv, trail = apply_path(base, s.derefs)
    if recv is None: return None, trail
    ent = FULL.get(recv, {}).get(s.slot)
    if ent is None: return None, "slot-not-in-%s" % recv
    owner, kind, name, sg, va = ent
    if va is None: return None, "slot-unresolved-in-%s" % recv
    return (recv, va, name, type_of_sig(parse_sig(sg)[1]),
            EVID.get(s.vkey, "?") + trail), None

def fixpoint():
    for _ in range(16):
        learned = 0
        for s in sites:
            k = ("ret", s.site)
            if k in TYPEOF: continue
            ok, _why = resolve_site(s)
            if ok and ok[3]: learned += learn(k, ok[3], "virtcall-ret")
        if not learned: return

fixpoint()

# ---- structural candidate sets ---------------------------------------------
# Sound constraint: for a value V, EVERY use site requires that the type T of V
#   (a) has a field at each byte offset the site dereferences, whose declared type
#       carries the next deref, and
#   (b) has the invoked slot in the merged slot table of the object the path lands on.
# A type failing any one site is impossible, so the TRUE type is always inside the
# candidate set. We therefore work in a candidate-set domain rather than insisting on
# a unique answer: a call site whose candidates all dispatch to one body is exactly
# resolved; one whose candidates dispatch to a handful of bodies still yields a sound
# OVER-approximation of the dependency edges, which is what a work-ordering graph needs
# (over-approximating can only make a function look less leaf-like than it is, never more).
key_sites = defaultdict(list)
for s in sites:
    if s.vkey and s.slot is not None:
        key_sites[s.vkey].append(s)

# cdecl stack cleanup after the call == 4 * (Self? + argument dwords). Verified against
# 2,235 already-exactly-resolved sites: 2,229 match to the byte (the 6 exceptions are
# Type Functions cleaning 4 bytes more than their signature accounts for), so this is a
# hard arity constraint on which slot bodies a call site can possibly be reaching.
def expected_cleanup(kind, sig):
    args, _ = parse_sig(sig)
    n = 1 if kind == "Method" else 0
    for a in args:
        n += 2 if a.strip() in ("l", "d") else 1
    return n * 4

def arity_ok(site, ent):
    if site.cleanup < 0: return True
    _o, kind, _n, sg, _v = ent
    exp = expected_cleanup(kind, sg)
    return site.cleanup == exp or (kind == "Function" and site.cleanup == exp + 4)

def compatible(t, ss):
    for s in ss:
        recv, _ = apply_path(t, s.derefs)
        if recv is None: return False
        ent = FULL.get(recv, {}).get(s.slot)
        if ent is None or not arity_ok(s, ent): return False
    return True

ALLT = sorted(ct_va)
CAND = {}
for k, ss in key_sites.items():
    if k in TYPEOF:
        CAND[k] = {TYPEOF[k]}
    else:
        CAND[k] = {t for t in ALLT if compatible(t, ss)}

# Second sound constraint on Globals: whatever is STORED into a Global must be
# assignable to it, so the Global's declared type is an ancestor of every stored
# value's static type. `mov [abs],reg` is the only way this codegen writes a Global,
# and NSS5CallGraph recorded all of them, so the union of ancestor sets is a valid
# upper bound. (Subtyping is why it is ancestors-of, not equal-to.)
def store_value_types(sv):
    """Possible static types of the value produced by the call at site `sv`."""
    u = type_from_helper(sv)
    if u: return {u}
    c = DIRECT_AT.get(sv)
    if c is not None:
        out = {type_of_sig(parse_sig(g)[1]) for (_t, _k, _n, g, _s) in addr2slot.get(c, [])}
        out.discard(None)
        if out: return out
    return set()

def value_types_at(sv):
    if ("ret", sv) in CAND: return CAND[("ret", sv)]
    return store_value_types(sv)

def apply_store_bounds():
    changed = 0
    for g, srcs in GSTORE_SRC.items():
        k = ("global", g)
        if k not in CAND or len(CAND[k]) == 1: continue
        b = set()
        for sv in srcs:
            for u in value_types_at(sv):
                b |= set(ancestry(u))
        if not b: continue
        n = CAND[k] & b
        if n and n != CAND[k]:
            CAND[k] = n; changed += 1
    return changed

apply_store_bounds()

def site_targets(s):
    """Sound set of possible callee addresses for one virtual call site."""
    cs = CAND.get(s.vkey)
    if not cs: return None
    out = set()
    for t in cs:
        recv, _ = apply_path(t, s.derefs)
        if recv is None: continue
        ent = FULL.get(recv, {}).get(s.slot)
        if ent is None or not arity_ok(s, ent): continue
        if ent[4]: out.add(ent[4])
        # a virtual call may land on an override in any subtype of the static type
        for sub in subtypes.get(recv, ()):
            e2 = FULL.get(sub, {}).get(s.slot)
            if e2 and e2[4]: out.add(e2[4])
    out.discard(ABSTRACT_STUB)
    return out

def ret_types(targets):
    out = set()
    for va in targets:
        for (_t, _k, _n, g, _s) in addr2slot.get(va, []):
            u = type_of_sig(parse_sig(g)[1])
            if u: out.add(u)
    return out

# Monotone narrowing: a call site tells us the possible return types of the call made
# there, which shrinks CAND for the ("ret", site) key, which can shrink further sites.
for _round in range(12):
    changed = 0
    for s in sites:
        k = ("ret", s.site)
        if k not in CAND: continue
        tg_ = site_targets(s)
        if not tg_: continue
        rts = ret_types(tg_)
        if not rts: continue
        new = CAND[k] & rts
        if new and new != CAND[k]:
            CAND[k] = new; changed += 1
    changed += apply_store_bounds()
    if not changed: break

for k, cs in CAND.items():
    if len(cs) == 1 and k not in TYPEOF:
        learn(k, next(iter(cs)), "structural-unique(%d sites)" % len(key_sites[k]))

for _ in range(6):
    fixpoint()
    if not seed_globals_from_stores(): break
fixpoint()
for k, ss in key_sites.items():
    if k in TYPEOF: CAND[k] = {TYPEOF[k]}
GLOBAL_TYPE = {k[1]: v for k, v in TYPEOF.items() if k[0] == "global"}

# ============================================================================
# 4. Emit edges
# ============================================================================
MAX_CAND_TARGETS = 12   # beyond this the site tells us nothing useful; call it unresolved

resolved_rows, unresolved_rows = [], []
edges, edge_kind = defaultdict(set), {}
certain = defaultdict(set)      # only edges we are sure of (direct / static / 1-target virtual)
unres_by_fn = defaultdict(int)

for r in direct:
    c, t = ihex(r["caller"]), ihex(r["callee"])
    edges[c].add(t); certain[c].add(t); edge_kind[(c, t)] = r["kind"]
    resolved_rows.append((r["caller"], r["site"], r["kind"], r["callee"],
                          label_of(t) or FN.get(t, {}).get("name", ""), "direct", "high"))
# `call dword ptr [0x00cXXXXX]` -- GCC folded (class table + slot) into an absolute
# memory operand. These are STATIC Type-Function calls, NOT imports: reading the dword
# at that address gives the callee outright, and if the address lands inside a known
# class table the receiver Type is named by (address - classtable_va).
CT_SORTED = sorted(ct_va.items(), key=lambda kv: kv[1])
CT_VAS = [v for _t, v in CT_SORTED]
import bisect
def classtable_owner(va):
    i = bisect.bisect_right(CT_VAS, va) - 1
    if i < 0: return None, None
    t, base = CT_SORTED[i]
    d = va - base
    return (t, d) if 0 <= d < 0x400 else (None, None)

n_iat = n_static = n_static_bad = 0
for r in indirect:
    if not (r["form"] == "abs" and r["vt"] == "0"): continue
    ptr = ihex(r["slot"])
    c = ihex(r["caller"])
    if ptr is None: continue
    if 0x00D00000 <= ptr < 0x00D02500:
        n_iat += 1
        resolved_rows.append((r["caller"], r["site"], "import", r["slot"], "IAT", "idata", "high"))
        continue
    tgt = rd32_at(ptr)
    if tgt is None or not (TEXT_LO <= tgt <= TEXT_HI or CODE_LO <= tgt < CODE_HI):
        n_static_bad += 1
        unresolved_rows.append((r["caller"], r["site"], r["slot"], "ABS", "abs-ptr-not-code", ""))
        unres_by_fn[c] += 1
        continue
    n_static += 1
    edges[c].add(tgt); certain[c].add(tgt); edge_kind.setdefault((c, tgt), "static")
    own, off = classtable_owner(ptr)
    resolved_rows.append((r["caller"], r["site"], "static", H(tgt),
                          label_of(tgt) or FN.get(tgt, {}).get("name", ""),
                          "classtable %s+%#x" % (own or "?", off or 0), "high"))

n_virt = n_exact = n_narrow = n_amb = 0
for s in sites:
    if s.slot is None:
        unresolved_rows.append((H(s.caller), H(s.site), "", s.term, "not-virtual-dispatch", s.chain))
        unres_by_fn[s.caller] += 1
        continue
    n_virt += 1
    seeded = s.vkey in TYPEOF
    tg_ = site_targets(s) if s.vkey else None
    if not tg_ or len(tg_) > MAX_CAND_TARGETS:
        why = ("terminal:" + s.term.split(":")[0].split("@")[0]) if not s.vkey else (
              "no-candidate-type" if not CAND.get(s.vkey) else
              ("cand-explosion(%d types,%d targets)" % (len(CAND[s.vkey]), len(tg_ or ()))))
        unresolved_rows.append((H(s.caller), H(s.site), "%#x" % s.slot, s.term, why, s.chain))
        unres_by_fn[s.caller] += 1
        continue
    if seeded and len(tg_) == 1:   conf, kind = "high", "virtual"; n_exact += 1
    elif len(tg_) == 1:            conf, kind = "narrowed", "virtual"; n_narrow += 1
    else:                          conf, kind = "cand%d" % len(tg_), "virtual-poly"; n_amb += 1
    recvs = sorted({apply_path(t, s.derefs)[0] for t in CAND[s.vkey]} - {None})
    for tv in tg_:
        edges[s.caller].add(tv); edge_kind.setdefault((s.caller, tv), "virtual")
        if len(tg_) == 1: certain[s.caller].add(tv)
    prim = sorted(tg_)[0]
    resolved_rows.append((H(s.caller), H(s.site), kind, H(prim),
                          label_of(prim) or "",
                          "%s|recv=%s|slot=%#x" % (EVID.get(s.vkey, "cand"),
                                                   ",".join(recvs[:4]), s.slot),
                          conf))
n_res = n_exact + n_narrow + n_amb
n_poly = n_amb

# ============================================================================
# 5. Layering over the in-scope (game) call graph
# ============================================================================

NODES = sorted(a for a in FN if in_game(a))
NSET  = set(NODES)
gedges = {a: {b for b in edges.get(a, ()) if b in NSET and b != a} for a in NODES}

# Tarjan SCC, iterative
index, low, onstk, stk, comp, cid = {}, {}, set(), [], {}, 0
counter = 0
for root in NODES:
    if root in index: continue
    work = [(root, iter(sorted(gedges[root])))]
    index[root] = low[root] = counter; counter += 1
    stk.append(root); onstk.add(root)
    while work:
        v, it = work[-1]
        adv = False
        for w in it:
            if w not in index:
                index[w] = low[w] = counter; counter += 1
                stk.append(w); onstk.add(w)
                work.append((w, iter(sorted(gedges[w]))))
                adv = True
                break
            elif w in onstk:
                low[v] = min(low[v], index[w])
        if adv: continue
        work.pop()
        if work:
            p = work[-1][0]
            low[p] = min(low[p], low[v])
        if low[v] == index[v]:
            while True:
                w = stk.pop(); onstk.discard(w); comp[w] = cid
                if w == v: break
            cid += 1

members = defaultdict(list)
for a, c in comp.items(): members[c].append(a)

cedges = defaultdict(set)
for a in NODES:
    for b in gedges[a]:
        if comp[a] != comp[b]: cedges[comp[a]].add(comp[b])

# layer(c) = 0 if no outgoing scc edges, else 1 + max(layer(succ))
layer, state = {}, {}
for c in range(cid):
    if c in layer: continue
    st = [c]
    while st:
        x = st[-1]
        if x in layer: st.pop(); continue
        pend = [y for y in cedges[x] if y not in layer]
        if pend:
            st.extend(pend[:1]); continue
        layer[x] = 0 if not cedges[x] else 1 + max(layer[y] for y in cedges[x])
        st.pop()

rev = defaultdict(set)
for a in NODES:
    for b in gedges[a]: rev[b].add(a)

# ---- robustness check: how much of the cyclic core survives if we keep ONLY
# ---- edges we are certain about (drop every over-approximated poly edge)?
cg2 = {a: {b for b in certain.get(a, ()) if b in NSET and b != a} for a in NODES}
c_index, c_low, c_on, c_stk, c_comp, c_cid, c_ctr = {}, {}, set(), [], {}, 0, 0
for root in NODES:
    if root in c_index: continue
    work = [(root, iter(sorted(cg2[root])))]
    c_index[root] = c_low[root] = c_ctr; c_ctr += 1
    c_stk.append(root); c_on.add(root)
    while work:
        v, it = work[-1]; adv = False
        for wnode in it:
            if wnode not in c_index:
                c_index[wnode] = c_low[wnode] = c_ctr; c_ctr += 1
                c_stk.append(wnode); c_on.add(wnode)
                work.append((wnode, iter(sorted(cg2[wnode])))); adv = True; break
            elif wnode in c_on:
                c_low[v] = min(c_low[v], c_index[wnode])
        if adv: continue
        work.pop()
        if work:
            p = work[-1][0]; c_low[p] = min(c_low[p], c_low[v])
        if c_low[v] == c_index[v]:
            while True:
                wnode = c_stk.pop(); c_on.discard(wnode); c_comp[wnode] = c_cid
                if wnode == v: break
            c_cid += 1
c_members = defaultdict(list)
for a, c in c_comp.items(): c_members[c].append(a)
CERTAIN_CYCLIC = sorted((len(v), k) for k, v in c_members.items() if len(v) > 1)

c_cedges = defaultdict(set)
for a in NODES:
    for bnode in cg2[a]:
        if c_comp[a] != c_comp[bnode]: c_cedges[c_comp[a]].add(c_comp[bnode])
c_layer = {}
for c in range(c_cid):
    if c in c_layer: continue
    st = [c]
    while st:
        x = st[-1]
        if x in c_layer: st.pop(); continue
        pend = [y for y in c_cedges[x] if y not in c_layer]
        if pend: st.extend(pend[:1]); continue
        c_layer[x] = 0 if not c_cedges[x] else 1 + max(c_layer[y] for y in c_cedges[x])
        st.pop()
LAYC = {a: c_layer[c_comp[a]] for a in NODES}

# ============================================================================
# 6. Type-level dependency graph (no disassembly needed)
# ============================================================================

tdeps = defaultdict(set)
for t in REAL_GAME_TYPES:
    for o, n, g in fields_of.get(t, []):
        u = elem_type_of_sig(g) or type_of_sig(g)
        if u and u != t: tdeps[t].add(u)
    for s, (k, n, g) in own_slots.get(t, {}).items():
        args, ret = parse_sig(g)
        for frag in args + [ret]:
            u = elem_type_of_sig(frag) or type_of_sig(frag)
            if u and u != t: tdeps[t].add(u)
    sup = super_of.get(t)
    if sup: tdeps[t].add(sup)

TN = sorted(REAL_GAME_TYPES)
TSET = set(TN)
tg = {t: {u for u in tdeps[t] if u in TSET and u != t} for t in TN}

tindex, tlow, tonstk, tstk, tcomp, tcid = {}, {}, set(), [], {}, 0
tc = 0
for root in TN:
    if root in tindex: continue
    work = [(root, iter(sorted(tg[root])))]
    tindex[root] = tlow[root] = tc; tc += 1
    tstk.append(root); tonstk.add(root)
    while work:
        v, it = work[-1]; adv = False
        for w in it:
            if w not in tindex:
                tindex[w] = tlow[w] = tc; tc += 1
                tstk.append(w); tonstk.add(w)
                work.append((w, iter(sorted(tg[w])))); adv = True; break
            elif w in tonstk:
                tlow[v] = min(tlow[v], tindex[w])
        if adv: continue
        work.pop()
        if work:
            p = work[-1][0]; tlow[p] = min(tlow[p], tlow[v])
        if tlow[v] == tindex[v]:
            while True:
                w = tstk.pop(); tonstk.discard(w); tcomp[w] = tcid
                if w == v: break
            tcid += 1

tmembers = defaultdict(list)
for t, c in tcomp.items(): tmembers[c].append(t)
tcedges = defaultdict(set)
for t in TN:
    for u in tg[t]:
        if tcomp[t] != tcomp[u]: tcedges[tcomp[t]].add(tcomp[u])
tlayer = {}
for c in range(tcid):
    if c in tlayer: continue
    st = [c]
    while st:
        x = st[-1]
        if x in tlayer: st.pop(); continue
        pend = [y for y in tcedges[x] if y not in tlayer]
        if pend: st.extend(pend[:1]); continue
        tlayer[x] = 0 if not tcedges[x] else 1 + max(tlayer[y] for y in tcedges[x])
        st.pop()

# ============================================================================
# 7. Vertical slice
# ============================================================================

def find_slot(tname, mname):
    for s, (o, k, n, g, va) in FULL.get(tname, {}).items():
        if n == mname: return va
    return None

# Entry: the game function(s) called from outside game code (the CRT / bbMain chain).
game_called = set()
for r in direct:
    c, t = ihex(r["caller"]), ihex(r["callee"])
    if in_game(t) and not in_game(c): game_called.add(t)

ROOTS = {}
for a in sorted(game_called):
    ROOTS["entry:" + (label_of(a) or H(a))] = a
for tn, mn in ANCHOR_METHODS:
    v = find_slot(tn, mn)
    if v: ROOTS["%s.%s" % (tn, mn)] = v

def reach(seeds, gr=None):
    gr = gr if gr is not None else gedges
    seen, dq = set(), deque(x for x in seeds if x in NSET)
    seen |= set(dq)
    while dq:
        x = dq.popleft()
        for y in gr[x]:
            if y not in seen: seen.add(y); dq.append(y)
    return seen

slice_all  = reach(ROOTS.values())
slice_cert = reach(ROOTS.values(), cg2)
slice_from = {nm: reach([v]) for nm, v in ROOTS.items()}

GROUP_SLICE = {}
ENTRY_ROOTS = [v for k, v in ROOTS.items() if k.startswith("entry:")]
for gname, tms in ANCHOR_GROUPS.items():
    seeds = [find_slot(a, b) for a, b in tms]
    seeds = [x for x in seeds if x]
    GROUP_SLICE[gname] = (reach(seeds), reach(seeds, cg2), seeds)
GROUP_SLICE["entry"] = (reach(ENTRY_ROOTS), reach(ENTRY_ROOTS, cg2), ENTRY_ROOTS)

# ============================================================================
# 8. Work units
# ============================================================================
# A work unit is a batch of functions one pass can own end to end. Rules:
#   - never split an SCC across units (a cycle has to be written together)
#   - group by declaring Type (the natural unit: shared fields, shared idioms)
#   - split a Type that is too big into slot-ordered chunks of <= MAX_UNIT
#   - a unit's dependencies are the units owning any in-scope callee
MAX_UNIT = 20

owner_of = {}
for a in NODES:
    ss = addr2slot.get(a)
    owner_of[a] = ss[0][0] if ss else "_free"

by_owner = defaultdict(list)
for a in NODES:
    by_owner[owner_of[a]].append(a)

MIN_UNIT = 5
raw = []
for t in sorted(by_owner):
    fns = sorted(by_owner[t], key=lambda a: (LAYC[a], a))
    for i in range(0, len(fns), MAX_UNIT):
        chunk = fns[i:i + MAX_UNIT]
        nm = t if len(fns) <= MAX_UNIT else "%s[%d]" % (t, i // MAX_UNIT + 1)
        raw.append(dict(name=nm, type=t, fns=chunk))

# Types with only a handful of slots do not justify a whole pass; bundle the small
# ones that sit at the same certain-layer into mixed units of up to MAX_UNIT functions.
big = [u for u in raw if len(u["fns"]) >= MIN_UNIT]
small = [u for u in raw if len(u["fns"]) < MIN_UNIT]
bybandsmall = defaultdict(list)
for u in small: bybandsmall[max(LAYC[a] for a in u["fns"])].append(u)
merged = []
for band in sorted(bybandsmall):
    cur = []
    for u in sorted(bybandsmall[band], key=lambda x: -len(x["fns"])):
        if sum(len(x["fns"]) for x in cur) + len(u["fns"]) > MAX_UNIT and cur:
            merged.append(cur); cur = []
        cur.append(u)
    if cur: merged.append(cur)
for grp in merged:
    big.append(dict(name="mixed:" + "+".join(x["type"] for x in grp)[:60],
                    type="(mixed)", fns=[a for x in grp for a in x["fns"]]))

units, unit_of = [], {}
for u in sorted(big, key=lambda x: (max(LAYC[a] for a in x["fns"]), -sum(FN[a]["size"] for a in x["fns"]))):
    uid = "U%03d" % (len(units) + 1)
    u["id"] = uid
    units.append(u)
    for a in u["fns"]: unit_of[a] = uid

uidx = {u["id"]: u for u in units}
for u in units:
    deps = set()
    for a in u["fns"]:
        for b in gedges[a]:
            if unit_of.get(b) and unit_of[b] != u["id"]: deps.add(unit_of[b])
    u["deps"] = deps
    u["bytes"] = sum(FN[a]["size"] for a in u["fns"])
    u["layer"] = max(LAYC[a] for a in u["fns"])
    u["layer_sound"] = max(layer[comp[a]] for a in u["fns"])
    u["cyclic"] = sum(1 for a in u["fns"] if len(members[comp[a]]) > 1)
    u["leaves"] = sum(1 for a in u["fns"] if not gedges[a])
    bts = u["bytes"]
    u["effort"] = ("S" if bts < 2000 else "M" if bts < 6000 else "L" if bts < 15000 else "XL")
    u["unres"] = sum(unres_by_fn.get(a, 0) for a in u["fns"])
    u["slice"] = sum(1 for a in u["fns"] if a in slice_all)

# ============================================================================
# 9. Write everything out
# ============================================================================

def w(path, header, rows):
    with io.open(os.path.join(EX, path), "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\t".join(header) + "\n")
        for r in rows:
            fh.write("\t".join("" if x is None else str(x) for x in r) + "\n")

w("callgraph_resolved.tsv",
  ["caller", "site", "kind", "callee", "callee_label", "evidence", "confidence"],
  resolved_rows)
w("callgraph_unresolved.tsv",
  ["caller", "site", "slot", "term", "reason", "chain"], unresolved_rows)
w("globals_typed.tsv", ["global", "type", "is_game", "nsites", "ncandidates", "candidates", "evidence"],
  [(H(g), GLOBAL_TYPE.get(g, ""), int(GLOBAL_TYPE.get(g, "") in GAME_TYPES),
    len(key_sites.get(("global", g), ())), len(CAND.get(("global", g), ())),
    ",".join(sorted(CAND.get(("global", g), ()))[:8]), EVID.get(("global", g), ""))
   for g in sorted(set(k[1] for k in key_sites if k[0] == "global") | set(GLOBAL_TYPE))])

w("dep_layers.tsv",
  ["addr", "label", "type", "size", "scc", "layer", "layer_certain", "n_callees",
   "n_callees_certain", "n_callers", "n_unresolved", "scc_size", "scc_size_certain",
   "in_slice", "unit"],
  [(H(a), label_of(a) or FN[a]["name"], owner_of[a], FN[a]["size"], comp[a],
    layer[comp[a]], LAYC[a], len(gedges[a]), len(cg2[a]), len(rev.get(a, ())),
    unres_by_fn.get(a, 0), len(members[comp[a]]), len(c_members[c_comp[a]]),
    int(a in slice_all), unit_of.get(a, "")) for a in NODES])

w("type_deps.tsv", ["type", "depends_on"],
  sorted((t, u) for t in TN for u in sorted(tg[t])))
w("type_layers.tsv", ["type", "scc", "layer", "scc_size", "n_deps", "n_dependents", "n_slots", "bytes"],
  sorted((t, tcomp[t], tlayer[tcomp[t]], len(tmembers[tcomp[t]]), len(tg[t]),
          sum(1 for u in TN if t in tg[u]), len(by_owner.get(t, ())),
          sum(FN[a]["size"] for a in by_owner.get(t, ()))) for t in TN))

leaves = [a for a in NODES if not gedges[a]]
w("leaves.tsv", ["addr", "label", "type", "size", "n_callers", "n_unresolved", "clean",
                 "n_runtime_calls", "unit"],
  [(H(a), label_of(a) or FN[a]["name"], owner_of[a], FN[a]["size"], len(rev.get(a, ())),
    unres_by_fn.get(a, 0), int(unres_by_fn.get(a, 0) == 0),
    len([b for b in edges.get(a, ()) if not in_game(b)]), unit_of.get(a, ""))
   for a in sorted(leaves, key=lambda x: (-int(unres_by_fn.get(x, 0) == 0), -FN[x]["size"]))])

w("vertical_slice.tsv",
  ["addr", "label", "type", "size", "layer_certain", "certain", "n_unresolved", "groups", "unit"],
  [(H(a), label_of(a) or FN[a]["name"], owner_of[a], FN[a]["size"], LAYC[a],
    int(a in slice_cert), unres_by_fn.get(a, 0),
    ",".join(g for g in ("entry", "boot", "menu", "data", "match") if a in GROUP_SLICE[g][0]),
    unit_of.get(a, ""))
   for a in sorted(slice_all, key=lambda x: (LAYC[x], x))])

w("work_units.tsv", ["unit", "name", "type", "layer", "layer_sound", "n_fns", "bytes",
                     "effort", "n_leaves", "n_cyclic", "n_unresolved", "n_in_slice",
                     "ready", "n_deps", "deps"],
  [(u["id"], u["name"], u["type"], u["layer"], u["layer_sound"], len(u["fns"]), u["bytes"],
    u["effort"], u["leaves"], u["cyclic"], u["unres"], u["slice"],
    int(not u["deps"]), len(u["deps"]), ",".join(sorted(u["deps"]))) for u in
   sorted(units, key=lambda x: (x["layer"], -x["bytes"]))])

w("work_unit_members.tsv", ["unit", "addr", "label", "size", "layer"],
  [(u["id"], H(a), label_of(a) or FN[a]["name"], FN[a]["size"], layer[comp[a]])
   for u in units for a in u["fns"]])

# ---- summary ---------------------------------------------------------------
n_ind = len(indirect)
print("== scope ==")
print("game functions in graph      : %d  (%d bytes)" % (len(NODES), sum(FN[a]["size"] for a in NODES)))
print("  known slots                : %d" % sum(1 for a in NODES if a in addr2slot))
print("  unattributed               : %d" % sum(1 for a in NODES if a not in addr2slot))
print("== edges ==")
print("direct call edges            : %d" % len(direct))
print("indirect call sites          : %d" % n_ind)
print("  IAT / import (.idata)      : %d" % n_iat)
print("  static Type-Function calls : %d  (call [classtable+slot], resolved outright)" % n_static)
print("     ... ptr not code        : %d" % n_static_bad)
print("  virtual dispatch sites     : %d" % n_virt)
print("  ... exactly resolved       : %d (%.1f%%)  [receiver type known, 1 target]" % (n_exact, 100.0*n_exact/max(1,n_virt)))
print("  ... narrowed to 1 target   : %d (%.1f%%)  [candidate set, all agree]" % (n_narrow, 100.0*n_narrow/max(1,n_virt)))
print("  ... 2..%d candidate targets : %d (%.1f%%)  [sound over-approximation]" % (MAX_CAND_TARGETS, n_amb, 100.0*n_amb/max(1,n_virt)))
print("  ... any target at all      : %d (%.1f%%)" % (n_res, 100.0*n_res/max(1,n_virt)))
print("  ... UNRESOLVED             : %d (%.1f%%)" % (n_virt - n_res, 100.0 * (n_virt - n_res) / max(1, n_virt)))
gv = [s for s in sites if s.slot is not None and in_game(s.caller)]
gvr = sum(1 for s in gv if site_targets(s) and len(site_targets(s)) <= MAX_CAND_TARGETS)
print("game-code virtual sites      : %d  resolved %d (%.1f%%)" % (len(gv), gvr, 100.0 * gvr / max(1, len(gv))))
print("== globals ==")
ng = len(set(k[1] for k in key_sites if k[0] == "global"))
print("global receivers observed    : %d  typed %d" % (ng, len(GLOBAL_TYPE)))
print("== layers ==")
print("SCCs                         : %d   max layer %d" % (cid, max(layer.values())))
big = sorted(((len(members[c]), c) for c in members), reverse=True)[:6]
print("largest SCCs                 : %s" % ", ".join("%dfn@L%d" % (n, layer[c]) for n, c in big))
print("cyclic functions             : %d in %d SCCs of size>1" %
      (sum(len(members[c]) for c in members if len(members[c]) > 1),
       sum(1 for c in members if len(members[c]) > 1)))
print("  certain-edges-only SCCs    : %s  (%d functions cyclic without any over-approximated edge)" %
      ([n for n, _c in CERTAIN_CYCLIC[-4:]], sum(n for n, _c in CERTAIN_CYCLIC)))
hist = defaultdict(int)
for a in NODES: hist[layer[comp[a]]] += 1
hist2 = defaultdict(int)
for a in NODES: hist2[LAYC[a]] += 1
print("layer histogram (certain)    : %s" % ", ".join("L%d=%d" % (k, hist2[k]) for k in sorted(hist2)))
print("max certain layer            : %d" % max(LAYC.values()))
print("layer histogram              : %s" % ", ".join("L%d=%d" % (k, hist[k]) for k in sorted(hist)))
print("leaves                       : %d  (clean %d)" %
      (len(leaves), sum(1 for a in leaves if unres_by_fn.get(a, 0) == 0)))
print("== vertical slice ==")
print("roots                        : %d" % len(ROOTS))
for nm in sorted(slice_from, key=lambda n: -len(slice_from[n]))[:8]:
    print("   %-34s -> %4d fns" % (nm, len(slice_from[nm])))
print("union reachable (sound)      : %d fns, %d bytes" %
      (len(slice_all), sum(FN[a]["size"] for a in slice_all)))
print("union reachable (certain)    : %d fns, %d bytes" %
      (len(slice_cert), sum(FN[a]["size"] for a in slice_cert)))
print("%-10s %6s %9s | %6s %9s" % ("group", "sound", "bytes", "certain", "bytes"))
for gname in ("entry", "boot", "menu", "data", "match"):
    A, B, sd = GROUP_SLICE[gname]
    print("%-10s %6d %9d | %6d %9d   (%d roots)" %
          (gname, len(A), sum(FN[a]["size"] for a in A),
           len(B), sum(FN[a]["size"] for a in B), len(sd)))
print("== types ==")
print("game types                   : %d  SCCs %d  max layer %d" % (len(TN), tcid, max(tlayer.values())))
tbig = sorted(((len(tmembers[c]), c) for c in tmembers), reverse=True)[:5]
print("largest type SCCs            : %s" % ", ".join("%dtypes@L%d" % (n, tlayer[c]) for n, c in tbig))
print("== work units ==")
print("units                        : %d   (%d..%d fns each)" %
      (len(units), min(len(u["fns"]) for u in units), max(len(u["fns"]) for u in units)))
print("effort mix                   : %s" % dict(__import__("collections").Counter(u["effort"] for u in units)))
print("layer-0 units                : %d" % sum(1 for u in units if u["layer"] == 0))
print("units with zero deps         : %d" % sum(1 for u in units if not u["deps"]))

# ============================================================================
# 10. Re-render docs/specs/11 from the TSVs just written  (--render)
# ============================================================================
# Deliberately reads the TSVs back off disk rather than reusing the in-memory
# structures above: the document is then provably a view of the published data,
# not of intermediate state that never reached a file.

def render_doc(template, dst):
    dl = rd_tsv(os.path.join(EX, 'dep_layers.tsv'))
    lv = rd_tsv(os.path.join(EX, 'leaves.tsv'))
    wu = rd_tsv(os.path.join(EX, 'work_units.tsv'))
    tl = rd_tsv(os.path.join(EX, 'type_layers.tsv'))
    vs = rd_tsv(os.path.join(EX, 'vertical_slice.tsv'))
    gt = rd_tsv(os.path.join(EX, 'globals_typed.tsv'))
    out = {}

    # ---- leaves, full list grouped by type ---------------------------------
    clean = [r for r in lv if r['clean'] == '1']
    byt = defaultdict(list)
    for r in clean: byt[r['type']].append(r)
    L = []
    for t in sorted(byt, key=lambda x: (-len(byt[x]), x)):
        rows = sorted(byt[t], key=lambda r: -int(r['size']))
        L.append('\n**%s** - %d leaves, %d bytes\n' % (t, len(rows), sum(int(r['size']) for r in rows)))
        L.append('')
        L.append('| addr | function | bytes | callers | unit |')
        L.append('|---|---|---:|---:|---|')
        for r in rows:
            L.append('| `%s` | `%s` | %s | %s | %s |' % (r['addr'], r['label'], r['size'], r['n_callers'], r['unit']))
    out['leaves_full'] = '\n'.join(L)

    b = Counter()
    for r in clean:
        n = int(r['size'])
        b['≥1024' if n >= 1024 else '512-1023' if n >= 512 else '256-511' if n >= 256
          else '128-255' if n >= 128 else '64-127' if n >= 64 else '<64'] += 1
    order = ['<64', '64-127', '128-255', '256-511', '512-1023', '≥1024']
    out['leaf_buckets'] = '\n'.join(
        ['| size band | count |', '|---|---:|'] + ['| %s | %d |' % (k, b[k]) for k in order])

    out['leaf_top'] = '\n'.join(
        ['| addr | function | bytes | callers |', '|---|---|---:|---:|'] +
        ['| `%s` | `%s` | %s | %s |' % (r['addr'], r['label'], r['size'], r['n_callers'])
         for r in sorted(clean, key=lambda r: -int(r['size']))[:40]])

    # ---- type layers -------------------------------------------------------
    byl = defaultdict(list)
    for r in tl: byl[int(r['layer'])].append(r)
    L = ['| layer | types | slots | bytes | members |', '|---:|---:|---:|---:|---|']
    for k in sorted(byl):
        rs = byl[k]
        L.append('| %d | %d | %d | %d | %s |' % (
            k, len(rs), sum(int(x['n_slots']) for x in rs), sum(int(x['bytes']) for x in rs),
            ' '.join('`%s`' % x['type'] for x in sorted(rs, key=lambda y: y['type']))))
    out['type_layers'] = '\n'.join(L)

    out['type_hubs'] = '\n'.join(
        ['| type | layer | slots | bytes | depends on | depended on by |', '|---|---:|---:|---:|---:|---:|'] +
        ['| `%s` | %s | %s | %s | %s | %s |' % (r['type'], r['layer'], r['n_slots'], r['bytes'],
                                                r['n_deps'], r['n_dependents'])
         for r in sorted(tl, key=lambda r: -int(r['n_dependents']))[:20]])

    # ---- function layers ---------------------------------------------------
    h = Counter(int(r['layer_certain']) for r in dl)
    hb = Counter(int(r['layer']) for r in dl)
    bb = defaultdict(int)
    for r in dl: bb[int(r['layer_certain'])] += int(r['size'])
    out['fn_layers'] = '\n'.join(
        ['| layer | functions (certain) | bytes (certain) | functions (sound) |', '|---:|---:|---:|---:|'] +
        ['| %d | %d | %d | %d |' % (k, h[k], bb[k], hb.get(k, 0)) for k in sorted(set(h) | set(hb))])

    # ---- work units --------------------------------------------------------
    def unit_table(rows):
        return '\n'.join(
            ['| unit | contents | layer | fns | bytes | effort | unresolved | in slice | deps |',
             '|---|---|---:|---:|---:|:---:|---:|---:|---|'] +
            ['| **%s** | `%s` | %s | %s | %s | %s | %s | %s | %s |' %
             (r['unit'], r['name'], r['layer'], r['n_fns'], r['bytes'], r['effort'],
              r['n_unresolved'], r['n_in_slice'],
              (r['deps'][:60] + '…') if len(r['deps']) > 60 else (r['deps'] or '-'))
             for r in rows])
    out['units_ready'] = unit_table([r for r in wu if r['ready'] == '1'])
    out['units_l0_l3'] = unit_table([r for r in wu if int(r['layer']) <= 3])
    out['units_all'] = unit_table(wu)
    out['unit_effort'] = '\n'.join(
        ['| effort | bytes | units | functions |', '|---|---|---:|---:|'] +
        ['| %s | %s | %d | %d |' % (e, rng,
                                    sum(1 for r in wu if r['effort'] == e),
                                    sum(int(r['n_fns']) for r in wu if r['effort'] == e))
         for e, rng in (('S', '< 2 000'), ('M', '2 000 - 5 999'), ('L', '6 000 - 14 999'), ('XL', '≥ 15 000'))])

    # ---- vertical slice ----------------------------------------------------
    cs = [r for r in vs if r['certain'] == '1']
    c = Counter(); bt = Counter()
    for r in cs: c[r['type']] += 1; bt[r['type']] += int(r['size'])
    out['slice_by_type'] = '\n'.join(
        ['| type | functions | bytes |', '|---|---:|---:|'] +
        ['| `%s` | %d | %d |' % (t, n, bt[t]) for t, n in c.most_common()])

    grp = defaultdict(lambda: [0, 0])
    for r in cs:
        for g in r['groups'].split(','):
            if g: grp[g][0] += 1; grp[g][1] += int(r['size'])

    matchonly = [r for r in cs if 'match' in r['groups']]
    out['slice_match'] = '\n'.join(
        ['| addr | function | type | bytes | layer |', '|---|---|---|---:|---:|'] +
        ['| `%s` | `%s` | %s | %s | %s |' % (r['addr'], r['label'], r['type'], r['size'], r['layer_certain'])
         for r in sorted(matchonly, key=lambda r: -int(r['size']))[:60]])

    # ---- globals -----------------------------------------------------------
    out['globals_top'] = '\n'.join(
        ['| global | inferred type | call sites | evidence |', '|---|---|---:|---|'] +
        ['| `%s` | `%s` | %s | %s |' % (r['global'], r['type'], r['nsites'], r['evidence'])
         for r in sorted([x for x in gt if x['type']], key=lambda x: -int(x['nsites']))[:25]])

    # ---- cycles ------------------------------------------------------------
    cyc = [r for r in dl if r['scc_size_certain'] != '1']
    out['cycles'] = '\n'.join(
        ['| addr | function | bytes | layer |', '|---|---|---:|---:|'] +
        ['| `%s` | `%s` | %s | %s |' % (r['addr'], r['label'], r['size'], r['layer_certain'])
         for r in sorted(cyc, key=lambda r: r['scc'])])

    bigscc = Counter(r['type'] for r in dl if r['scc_size'] == '242')
    out['bigscc'] = '\n'.join(
        ['| type | functions in the SCC |', '|---|---:|'] +
        ['| `%s` | %d |' % (t, n) for t, n in bigscc.most_common()])

    src = io.open(template, encoding='utf-8').read()
    for k, v in out.items():
        src = src.replace('<<<%s>>>' % k, v)
    io.open(dst, 'w', encoding='utf-8', newline='\n').write(src)
    print('wrote', dst, len(src), 'chars')
    for k in out:
        if '<<<%s>>>' % k in src: print('UNSUBSTITUTED', k)


if RENDER:
    render_doc(POSARGS[0] if POSARGS else TEMPLATE,
               POSARGS[1] if len(POSARGS) > 1 else TARGET)
