#!/usr/bin/env python3
"""
status.py -- the per-function record store, designed for MANY CONCURRENT WRITERS.

    python scripts/status.py seed                       # create every record, once
    python scripts/status.py claim   --va 004d8aba --worker a17
    python scripts/status.py release --va 004d8aba --worker a17
    python scripts/status.py set     --va 004d8aba --status verified \
                                     --oracle C:vectors/TFormation.GetRow.tsv \
                                     --confidence high --note "..." --worker a17
    python scripts/status.py next    --worker a17 --count 5 [--type TFormation]
    python scripts/status.py rollup                      # regenerate the summary

LAYOUT AND WHY

  status/fn/<key>.json     ONE FILE PER FUNCTION. The key is the VA: slot ->
                           address is 1:1 with zero collisions for every slot
                           that has a real body, so the filename is unique by
                           construction. (The 7 abstract slots all share the
                           thrower 0x005B95AC and are keyed abs-<Type>-<slot>
                           instead -- see key_for.) One function is exactly one
                           pass's unit of work, so the file has exactly one
                           writer and there is NOTHING TO MERGE, ever.

  status/claims/<va>.claim Created with open(..,'x') -- an atomic create-if-not-
                           exists. That is the whole lock. One file per claim
                           means claiming never contends either.

  status/log/<pass>.jsonl Append-only event log, one file per pass. Never read
                           by the pipeline; it exists so a bad batch can be
                           attributed and rolled back.

  status/_rollup.tsv       GENERATED by concatenation. Never hand-edit it; any
                           edit is overwritten by the next `rollup`.

REJECTED ALTERNATIVES, and why they fail at this scale:

  one big status.tsv       Guaranteed lost updates. Two passes read the same 1,600
                           rows, each rewrites the whole file, the second wins and
                           silently discards the first. No locking primitive is
                           available that every pass will reliably honour.

  one file per TYPE        This is what methodology sec 6.2 proposed, and it is a
                           real improvement on one big file -- but it reintroduces
                           contention exactly where the work is densest. TPlayer
                           has 135 members; you want ten passes on TPlayer, and
                           they would all be rewriting one TSV. It also forces a
                           read-modify-write of other passes' rows, which is the
                           specific operation that loses data.

  append-only log only     Zero contention and perfect history, but "what is the
                           state of function X" becomes a fold over every log
                           file. Fine for audit, too slow and too error-prone as
                           the primary store.

  So: per-function JSON as the state, per-pass JSONL as the history, generated
  rollup as the view. The write path never touches a file another pass may write.
"""

import argparse
import json
import os
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATUS = os.path.join(ROOT, "status")
FN_DIR = os.path.join(STATUS, "fn")
CLAIM_DIR = os.path.join(STATUS, "claims")
LOG_DIR = os.path.join(STATUS, "log")
VTABLE_MAP = os.path.join(ROOT, "extracted", "vtable_map.tsv")
CLASS_TABLES = os.path.join(ROOT, "extracted", "class_tables.tsv")
DECOMP = os.path.join(ROOT, "extracted", "decomp")

GAME_TYPE_CUTOFF = 0x00C94988
ABSTRACT_STUB = "0x005b95ac"

STATES = ("unknown", "located", "decompiled", "mapped", "written", "compiles",
          "verified", "abstract", "n/a-gc", "blocked")


def game_types():
    out = set()
    with open(CLASS_TABLES, encoding="utf-8-sig") as fh:
        fh.readline()
        for line in fh:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 2 and int(p[1], 16) < GAME_TYPE_CUTOFF \
                    and not p[0].startswith("z_"):
                out.add(p[0])
    return out


def slots():
    with open(VTABLE_MAP, encoding="utf-8-sig") as fh:
        fh.readline()
        for line in fh:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 7:
                yield dict(type=p[0], kind=p[1], name=p[2], sig=p[3],
                           slot=p[4], va=p[5], vstatus=p[6])


def key_for(va, type_name=None, slot=None):
    """Record key. Normally the VA -- the resolver proved slot -> address is 1:1
    with no collisions for every slot that has a real body.

    EXCEPTION, and it matters: all 7 abstract game slots point at the SAME shared
    thrower 0x005B95AC. Keying those by VA collapses seven distinct declarations
    into one file and loses six of them (observed: the first seed produced 1 of
    the 7). Abstract slots are therefore keyed by Type+slot instead."""
    v = va.replace("0x", "").lower()
    if v == ABSTRACT_STUB.replace("0x", ""):
        return "abs-%s-%s" % (type_name, str(slot).replace("0x", ""))
    return v


def path_for(key):
    return os.path.join(FN_DIR, key + ".json")


def load(key):
    p = path_for(key)
    if not os.path.isfile(p):
        return None
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def save(rec):
    os.makedirs(FN_DIR, exist_ok=True)
    key = key_for(rec["va"], rec.get("type"), rec.get("slot"))
    tmp = path_for(key) + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(rec, fh, indent=1, default=str)
    os.replace(tmp, path_for(key))             # atomic on Windows and POSIX


def log(worker, event):
    os.makedirs(LOG_DIR, exist_ok=True)
    with open(os.path.join(LOG_DIR, "%s.jsonl" % worker), "a",
              encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps(event, default=str) + "\n")


def decomp_for(rec):
    fn = "%s.%s@%s.c" % (rec["type"], rec["member"], rec["va"].replace("0x", ""))
    p = os.path.join(DECOMP, fn)
    return os.path.relpath(p, ROOT).replace("\\", "/") if os.path.isfile(p) else None


# ------------------------------------------------------------------ subcommands

def cmd_seed(args):
    os.makedirs(FN_DIR, exist_ok=True)
    gt = game_types()
    made = kept = refreshed = 0
    for s in slots():
        if s["type"] not in gt or not s["va"]:
            continue
        if s["vstatus"] == "ABSTRACT" or s["va"].lower() == ABSTRACT_STUB:
            st = "abstract"
        elif s["vstatus"] == "OK":
            st = "located"
        else:
            continue
        existing = load(key_for(s["va"], s["type"], s["slot"]))
        if existing is not None:
            # Idempotent refresh. The decompilation corpus is exported by a
            # separate, long-running Ghidra pass, so a record seeded before its
            # .c file landed would be stuck at `located` forever. Only records
            # NO PASS HAS TOUCHED are refreshed -- never write over a file that
            # another pass owns, which is the whole point of one-file-per-
            # function.
            if existing.get("pass") is None:
                d = decomp_for(existing)
                if d and existing.get("decomp") != d:
                    existing["decomp"] = d
                    if existing["status"] == "located":
                        existing["status"] = "decompiled"
                    save(existing)
                    refreshed += 1
            kept += 1
            continue
        rec = dict(schema=1, va=s["va"], type=s["type"], member=s["name"],
                   kind=s["kind"], sig=s["sig"], slot=s["slot"],
                   layer=None, status=st, src_file=None,
                   t1=None, t2_sig=None, t3=None, t4=None,
                   similarity=None, oracle=None, confidence=None,
                   uncertain=[], notes=[], worker=None, updated=None)
        rec["decomp"] = decomp_for(rec)
        if rec["decomp"] and st == "located":
            rec["status"] = "decompiled"
        save(rec)
        made += 1
    print("seeded %d new, refreshed %d, %d already current, in %s"
          % (made, refreshed, kept - refreshed, FN_DIR))
    print("denominator: report progress against these, NOT against all 2,809 slots")
    print("(the other 1,050 belong to BRL/PUB/3rd-party types that NG supplies)")
    return 0


def cmd_claim(args):
    os.makedirs(CLAIM_DIR, exist_ok=True)
    p = os.path.join(CLAIM_DIR, args.va.replace("0x", "").lower() + ".claim")
    try:
        with open(p, "x", encoding="utf-8", newline="\n") as fh:      # atomic
            fh.write("%s\t%s\n" % (getattr(args, "worker"),
                                   time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())))
    except FileExistsError:
        with open(p, encoding="utf-8") as fh:
            print("ALREADY CLAIMED by %s" % fh.read().strip())
        return 1
    print("claimed %s for %s" % (args.va, getattr(args, "worker")))
    return 0


def cmd_release(args):
    p = os.path.join(CLAIM_DIR, args.va.replace("0x", "").lower() + ".claim")
    if os.path.isfile(p):
        os.remove(p)
        print("released %s" % args.va)
        return 0
    print("no claim on %s" % args.va)
    return 1


def cmd_set(args):
    rec = load(key_for(args.va, args.type, args.slot))
    if rec is None:
        print("no record for %s -- run `status.py seed` first" % args.va)
        return 2
    if args.status and args.status not in STATES:
        print("bad status %r; one of %s" % (args.status, ", ".join(STATES)))
        return 2
    for k in ("status", "src_file", "oracle", "confidence", "layer"):
        v = getattr(args, k, None)
        if v is not None:
            rec[k] = v
    if args.similarity is not None:
        rec["similarity"] = args.similarity
    for n in args.note or []:
        rec["notes"].append(n)
    for u in args.uncertain or []:
        rec["uncertain"].append("UNCERTAIN: " + u if not u.startswith("UNCERTAIN:") else u)
    rec["worker"] = getattr(args, "worker")
    rec["updated"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    save(rec)
    log(getattr(args, "worker"), dict(ts=rec["updated"], va=rec["va"], status=rec["status"],
                         similarity=rec["similarity"], notes=args.note or []))
    print(json.dumps(rec, indent=1, default=str))
    return 0


def cmd_next(args):
    claimed = set()
    if os.path.isdir(CLAIM_DIR):
        claimed = set(f[:-6] for f in os.listdir(CLAIM_DIR) if f.endswith(".claim"))
    out = []
    for f in sorted(os.listdir(FN_DIR)) if os.path.isdir(FN_DIR) else []:
        if not f.endswith(".json"):
            continue
        key = f[:-5]
        if key in claimed:
            continue
        with open(os.path.join(FN_DIR, f), encoding="utf-8") as fh:
            rec = json.load(fh)
        if rec["status"] in ("verified", "abstract", "n/a-gc"):
            continue
        if args.type and rec["type"] != args.type:
            continue
        out.append(rec)
        if len(out) >= args.count:
            break
    for rec in out:
        print("%s\t%s.%s\t%s\t%s\t%s"
              % (rec["va"], rec["type"], rec["member"], rec["sig"],
                 rec["status"], rec.get("decomp") or "-"))
    return 0


def cmd_rollup(args):
    recs = []
    if os.path.isdir(FN_DIR):
        for f in sorted(os.listdir(FN_DIR)):
            if f.endswith(".json"):
                with open(os.path.join(FN_DIR, f), encoding="utf-8") as fh:
                    recs.append(json.load(fh))
    os.makedirs(STATUS, exist_ok=True)
    tsv = os.path.join(STATUS, "_rollup.tsv")
    with open(tsv, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("va\ttype\tmember\tkind\tsig\tslot\tstatus\tsimilarity\t"
                 "confidence\tsrc_file\toracle\tagent\tupdated\tuncertain\n")
        for r in sorted(recs, key=lambda x: (x["type"], x["slot"])):
            fh.write("\t".join(str(x) if x is not None else "" for x in [
                r["va"], r["type"], r["member"], r["kind"], r["sig"], r["slot"],
                r["status"], r.get("similarity"), r.get("confidence"),
                r.get("src_file"), r.get("oracle"), r.get("pass"), r.get("updated"),
                len(r.get("uncertain") or [])]) + "\n")
    counts = {}
    for r in recs:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    total = len(recs)
    reconstructable = sum(v for k, v in counts.items() if k not in ("abstract", "n/a-gc"))
    print("records: %d   (reconstructable denominator: %d)" % (total, reconstructable))
    for k in STATES:
        if counts.get(k):
            print("  %-12s %5d" % (k, counts[k]))
    scored = [r["similarity"] for r in recs if r.get("similarity") is not None]
    if scored:
        print("  T3 scored    %5d   median %.3f   below 0.30: %d"
              % (len(scored), sorted(scored)[len(scored) // 2],
                 sum(1 for s in scored if s < 0.30)))
    unc = sum(len(r.get("uncertain") or []) for r in recs)
    print("  UNCERTAIN flags outstanding: %d" % unc)
    print("wrote %s" % tsv)
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("seed")
    for name in ("claim", "release"):
        p = sub.add_parser(name)
        p.add_argument("--va", required=True)
        p.add_argument("--worker", required=True)
    p = sub.add_parser("set")
    p.add_argument("--va", required=True)
    p.add_argument("--worker", required=True)
    p.add_argument("--type", help="only needed for an abstract slot (shared VA)")
    p.add_argument("--slot", help="only needed for an abstract slot (shared VA)")
    p.add_argument("--status")
    p.add_argument("--src-file", dest="src_file")
    p.add_argument("--oracle")
    p.add_argument("--confidence", choices=["high", "medium", "low"])
    p.add_argument("--layer")
    p.add_argument("--similarity", type=float)
    p.add_argument("--note", action="append")
    p.add_argument("--uncertain", action="append")
    p = sub.add_parser("next")
    p.add_argument("--worker", required=True)
    p.add_argument("--count", type=int, default=5)
    p.add_argument("--type")
    sub.add_parser("rollup")

    args = ap.parse_args()
    return dict(seed=cmd_seed, claim=cmd_claim, release=cmd_release,
                set=cmd_set, next=cmd_next, rollup=cmd_rollup)[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
